java_binary(
    name = "verify_diagnostics_output",
    srcs = ["VerifyDiagnosticsOutput.java"],
    deps = [
        "//src/protobuf/io/bazel/rules_scala:diagnostics_java_proto",
    ],
    main_class = "diagnostics_reporter.VerifyDiagnosticsOutput",
    visibility = ["//visibility:public"],
)