java_binary(
    name = "diagnostics_reporter_test",
    srcs = ["VerifyDiagnosticsOutput.java", "DiagnosticsReporterTest.java"],
    deps = [
        "//src/protobuf/io/bazel/rules_scala:diagnostics_java_proto",
    ],
    main_class = "diagnostics_reporter.DiagnosticsReporterTest",
    visibility = ["//visibility:public"],
)