java_library(
    name = "worker",
    srcs = ["Worker.java"],
    deps = [
        "@io_bazel_rules_scala//src/java/com/google/devtools/build/lib:worker",
    ],
    visibility = ["//src:__subpackages__"]
)