load(":toolchain_dep_rules.bzl", "common_toolchain_deps")

# dependencies from ScalacProvider
common_toolchain_deps(
    name = "scala_compile_classpath",
    provider_id = "scala_compile_classpath",
    visibility = ["//visibility:public"],
)

common_toolchain_deps(
    name = "scala_library_classpath",
    provider_id = "scala_library_classpath",
    visibility = ["//visibility:public"],
)

common_toolchain_deps(
    name = "scala_xml",
    provider_id = "scala_xml",
    visibility = ["//visibility:public"],
)

common_toolchain_deps(
    name = "parser_combinators",
    provider_id = "parser_combinators",
    visibility = ["//visibility:public"],
)
