load("//scala:scala.bzl", "scala_junit_test")

scala_junit_test(
    name = "failing_test",
    srcs = ["JunitFailureTest.scala"],
    suffixes = ["Test"],
    size = "small",
)
scala_junit_test(
    name = "no_prefix_or_suffix",
    srcs = ["JunitTest.scala"],
    size = "small",
)
