load("//tut_rule:tut.bzl", "scala_tut_doc")
load("//scala:scala.bzl", "scala_library")

scala_library(
    name = "test_dep",
    srcs = ["TestDep.scala"],
)

#scala_tut_doc(
#    name = "some_example",
#    src = "SomeExample.md",
#    deps = [":test_dep"],
#)
