load("//thrift:thrift.bzl", "thrift_library")

thrift_library(
    name = "bare_jar_1",
    srcs = ["//test/src/main/resources/scalarules/test:Bar.thrift"],
    visibility = ["//visibility:public"],
)
