load(
    "//scala/private:rules/scala_service_provider.bzl",
    "scala_service_provider_singleton",
)

scala_service_provider_singleton(
    name = "phase_write_services_files",
    visibility = ["//visibility:public"],
)
