load("//repositories:bazel_skylib.bzl", "load_bazel_skylib")

load_bazel_skylib()

load("//repositories:rules_jvm_external.bzl", "load_rules_jvm_external")

load_rules_jvm_external()

load("//repositories:rules_scala.bzl", "load_rules_scala")

load_rules_scala()

load("//repositories:rules_proto.bzl", "load_rules_proto")

load_rules_proto()

load("//repositories:rules_python.bzl", "load_rules_python")

load_rules_python()

load(
    "@io_bazel_rules_scala//unstable/multiscala:configuration.bzl",
    "multiscala_configuration",
)

multiscala_configuration(configuration = {
    "default": "2.12",
    "scala": {
        "2.11": {
            "minor": "12",
        },
        "2.12": {
            "minor": "10",
        },
        "2.13": {
            "minor": "1",
            "scala_bootstrap_toolchain": {
                "scalacopts": [
                    "-deprecation:true",
                    "-encoding",
                    "UTF-8",
                    "-feature",
                    "-unchecked",
                    "-Xfatal-warnings",
                    "-Xsource:2.13",
                ],
            },
        },
    },
    "scala-parser-combinators": "1.1.2",
    "scala-xml": "1.2.0",
    "scala_bootstrap_toolchain": {
        "scalacopts": [
            "-deprecation:true",
            "-encoding",
            "UTF-8",
            "-feature",
            "-unchecked",
            "-Xfatal-warnings",
            "-Xfuture",
            "-Xsource:2.12",
            "-Ypartial-unification",
        ],
    },
    "scala_toolchain": {
        "unused_dependency_checker_mode": "error",
    },
    "scalatest": "3.1.0",
    "scalactic": "3.1.0",
})

load("@io_bazel_rules_scala//unstable/multiscala:repositories.bzl", "create_repositories")

create_repositories()

load("@io_bazel_rules_scala//unstable/multiscala:configure.bzl", "multiscala_configure")

multiscala_configure()
