package scalarules.test.junit.specs2

import org.specs2.mutable.SpecWithJUnit

class JunitSpecs2LargeTest extends SpecWithJUnit {
  "run in bazel no: 0" in { success }
  "run in bazel no: 1" in { success }
  "run in bazel no: 2" in { success }
  "run in bazel no: 3" in { success }
  "run in bazel no: 4" in { success }
  "run in bazel no: 5" in { success }
  "run in bazel no: 6" in { success }
  "run in bazel no: 7" in { success }
  "run in bazel no: 8" in { success }
  "run in bazel no: 9" in { success }
  "run in bazel no: 10" in { success }
  "run in bazel no: 11" in { success }
  "run in bazel no: 12" in { success }
  "run in bazel no: 13" in { success }
  "run in bazel no: 14" in { success }
  "run in bazel no: 15" in { success }
  "run in bazel no: 16" in { success }
  "run in bazel no: 17" in { success }
  "run in bazel no: 18" in { success }
  "run in bazel no: 19" in { success }
  "run in bazel no: 20" in { success }
  "run in bazel no: 21" in { success }
  "run in bazel no: 22" in { success }
  "run in bazel no: 23" in { success }
  "run in bazel no: 24" in { success }
  "run in bazel no: 25" in { success }
  "run in bazel no: 26" in { success }
  "run in bazel no: 27" in { success }
  "run in bazel no: 28" in { success }
  "run in bazel no: 29" in { success }
  "run in bazel no: 30" in { success }
  "run in bazel no: 31" in { success }
  "run in bazel no: 32" in { success }
  "run in bazel no: 33" in { success }
  "run in bazel no: 34" in { success }
  "run in bazel no: 35" in { success }
  "run in bazel no: 36" in { success }
  "run in bazel no: 37" in { success }
  "run in bazel no: 38" in { success }
  "run in bazel no: 39" in { success }
  "run in bazel no: 40" in { success }
  "run in bazel no: 41" in { success }
  "run in bazel no: 42" in { success }
  "run in bazel no: 43" in { success }
  "run in bazel no: 44" in { success }
  "run in bazel no: 45" in { success }
  "run in bazel no: 46" in { success }
  "run in bazel no: 47" in { success }
  "run in bazel no: 48" in { success }
  "run in bazel no: 49" in { success }
  "run in bazel no: 50" in { success }
  "run in bazel no: 51" in { success }
  "run in bazel no: 52" in { success }
  "run in bazel no: 53" in { success }
  "run in bazel no: 54" in { success }
  "run in bazel no: 55" in { success }
  "run in bazel no: 56" in { success }
  "run in bazel no: 57" in { success }
  "run in bazel no: 58" in { success }
  "run in bazel no: 59" in { success }
  "run in bazel no: 60" in { success }
  "run in bazel no: 61" in { success }
  "run in bazel no: 62" in { success }
  "run in bazel no: 63" in { success }
  "run in bazel no: 64" in { success }
  "run in bazel no: 65" in { success }
  "run in bazel no: 66" in { success }
  "run in bazel no: 67" in { success }
  "run in bazel no: 68" in { success }
  "run in bazel no: 69" in { success }
  "run in bazel no: 70" in { success }
  "run in bazel no: 71" in { success }
  "run in bazel no: 72" in { success }
  "run in bazel no: 73" in { success }
  "run in bazel no: 74" in { success }
  "run in bazel no: 75" in { success }
  "run in bazel no: 76" in { success }
  "run in bazel no: 77" in { success }
  "run in bazel no: 78" in { success }
  "run in bazel no: 79" in { success }
  "run in bazel no: 80" in { success }
  "run in bazel no: 81" in { success }
  "run in bazel no: 82" in { success }
  "run in bazel no: 83" in { success }
  "run in bazel no: 84" in { success }
  "run in bazel no: 85" in { success }
  "run in bazel no: 86" in { success }
  "run in bazel no: 87" in { success }
  "run in bazel no: 88" in { success }
  "run in bazel no: 89" in { success }
  "run in bazel no: 90" in { success }
  "run in bazel no: 91" in { success }
  "run in bazel no: 92" in { success }
  "run in bazel no: 93" in { success }
  "run in bazel no: 94" in { success }
  "run in bazel no: 95" in { success }
  "run in bazel no: 96" in { success }
  "run in bazel no: 97" in { success }
  "run in bazel no: 98" in { success }
  "run in bazel no: 99" in { success }
  "run in bazel no: 100" in { success }
  "run in bazel no: 101" in { success }
  "run in bazel no: 102" in { success }
  "run in bazel no: 103" in { success }
  "run in bazel no: 104" in { success }
  "run in bazel no: 105" in { success }
  "run in bazel no: 106" in { success }
  "run in bazel no: 107" in { success }
  "run in bazel no: 108" in { success }
  "run in bazel no: 109" in { success }
  "run in bazel no: 110" in { success }
  "run in bazel no: 111" in { success }
  "run in bazel no: 112" in { success }
  "run in bazel no: 113" in { success }
  "run in bazel no: 114" in { success }
  "run in bazel no: 115" in { success }
  "run in bazel no: 116" in { success }
  "run in bazel no: 117" in { success }
  "run in bazel no: 118" in { success }
  "run in bazel no: 119" in { success }
  "run in bazel no: 120" in { success }
  "run in bazel no: 121" in { success }
  "run in bazel no: 122" in { success }
  "run in bazel no: 123" in { success }
  "run in bazel no: 124" in { success }
  "run in bazel no: 125" in { success }
  "run in bazel no: 126" in { success }
  "run in bazel no: 127" in { success }
  "run in bazel no: 128" in { success }
  "run in bazel no: 129" in { success }
  "run in bazel no: 130" in { success }
  "run in bazel no: 131" in { success }
  "run in bazel no: 132" in { success }
  "run in bazel no: 133" in { success }
  "run in bazel no: 134" in { success }
  "run in bazel no: 135" in { success }
  "run in bazel no: 136" in { success }
  "run in bazel no: 137" in { success }
  "run in bazel no: 138" in { success }
  "run in bazel no: 139" in { success }
  "run in bazel no: 140" in { success }
  "run in bazel no: 141" in { success }
  "run in bazel no: 142" in { success }
  "run in bazel no: 143" in { success }
  "run in bazel no: 144" in { success }
  "run in bazel no: 145" in { success }
  "run in bazel no: 146" in { success }
  "run in bazel no: 147" in { success }
  "run in bazel no: 148" in { success }
  "run in bazel no: 149" in { success }
  "run in bazel no: 150" in { success }
  "run in bazel no: 151" in { success }
  "run in bazel no: 152" in { success }
  "run in bazel no: 153" in { success }
  "run in bazel no: 154" in { success }
  "run in bazel no: 155" in { success }
  "run in bazel no: 156" in { success }
  "run in bazel no: 157" in { success }
  "run in bazel no: 158" in { success }
  "run in bazel no: 159" in { success }
  "run in bazel no: 160" in { success }
  "run in bazel no: 161" in { success }
  "run in bazel no: 162" in { success }
  "run in bazel no: 163" in { success }
  "run in bazel no: 164" in { success }
  "run in bazel no: 165" in { success }
  "run in bazel no: 166" in { success }
  "run in bazel no: 167" in { success }
  "run in bazel no: 168" in { success }
  "run in bazel no: 169" in { success }
  "run in bazel no: 170" in { success }
  "run in bazel no: 171" in { success }
  "run in bazel no: 172" in { success }
  "run in bazel no: 173" in { success }
  "run in bazel no: 174" in { success }
  "run in bazel no: 175" in { success }
  "run in bazel no: 176" in { success }
  "run in bazel no: 177" in { success }
  "run in bazel no: 178" in { success }
  "run in bazel no: 179" in { success }
  "run in bazel no: 180" in { success }
  "run in bazel no: 181" in { success }
  "run in bazel no: 182" in { success }
  "run in bazel no: 183" in { success }
  "run in bazel no: 184" in { success }
  "run in bazel no: 185" in { success }
  "run in bazel no: 186" in { success }
  "run in bazel no: 187" in { success }
  "run in bazel no: 188" in { success }
  "run in bazel no: 189" in { success }
  "run in bazel no: 190" in { success }
  "run in bazel no: 191" in { success }
  "run in bazel no: 192" in { success }
  "run in bazel no: 193" in { success }
  "run in bazel no: 194" in { success }
  "run in bazel no: 195" in { success }
  "run in bazel no: 196" in { success }
  "run in bazel no: 197" in { success }
  "run in bazel no: 198" in { success }
  "run in bazel no: 199" in { success }
}