load("//scala/settings:stamp_settings.bzl", "stamp_scala_import")

stamp_scala_import(
    name = "stamp_scala_import_on",
    build_setting_default = True,
    visibility = ["//visibility:public"],
)

stamp_scala_import(
    name = "stamp_scala_import_off",
    build_setting_default = False,
    visibility = ["//visibility:public"],
)
