load("//scala:scala.bzl", "scala_library")

scala_library(
    name = "source_jar_not_oncp",
    srcs = ["ReferCatsImplicits.scala"],
    deps = [
        "@maven//:org_typelevel_cats_core_2_11",
    ],
)
