load("//scala:scala.bzl", "scala_library")

scala_library(
    name = "source_jar_not_oncp",
    testonly = True,
    srcs = ["ReferCatsImplicits.scala"],
    deps = [
        "@org_typelevel__cats_core//jar",
        "@org_typelevel__cats_kernel",
    ],
)
