proto_library(
    name = "diagnostics_proto",
    srcs = ["diagnostics.proto"],
)

java_proto_library(
    name = "diagnostics_java_proto",
    deps = [":diagnostics_proto"],
    visibility = ["//visibility:public"],
)
