
java_binary(
    name="runner",
    srcs = ["Runner.java"],
    deps = [
         "//external:io_bazel_rules_scala/dependency/scalatest/scalatest"
    ],
        visibility = ["//visibility:public"]
)