java_library(
    name = "runner",
    srcs = ["Runner.java"],
    visibility = ["//visibility:public"],
    deps = [
        "//external:io_bazel_rules_scala/dependency/scalatest/scalatest",
    ],
)
