load("@rules_java//java:defs.bzl", "java_import")

java_import(
    name = "example_jar1",
    jars = [
        "example_jar1.jar",
    ],
    visibility = ["//visibility:public"],
)

java_import(
    name = "example_jar2",
    jars = [
        "example_jar2.jar",
    ],
    visibility = ["//visibility:public"],
)
