java_library(
    name = "worker",
    srcs = [
        "GenericWorker.java",
        "Processor.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//third_party/bazel/src/main/protobuf:worker_protocol_java_proto",
    ],
)
