load("@io_bazel_rules_scala//tut_rule:tut.bzl", "scala_tut_doc")
load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library")

scala_library(
    name = "test_dep",
    srcs = ["TestDep.scala"],
)

#scala_tut_doc(
    #name = "some_example",
    #src = "SomeExample.md",
    #deps = [":test_dep"],
#)
