java_library(
    name = "reporter",
    srcs = ["DepsTrackingReporter.java"],
    visibility = ["//visibility:public"],
    deps = [
        "//scala/private/toolchain_deps:scala_compile_classpath",
        "//src/java/io/bazel/rulesscala/scalac/compileoptions",
    ],
)
