workspace(name = "test_dt_patches")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_jar")

http_archive(
    name = "bazel_skylib",
    sha256 = "b8a1527901774180afc798aeb28c4634bdccf19c4d98e7bdd1ce79d1fe9aaad7",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.4.1/bazel-skylib-1.4.1.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.4.1/bazel-skylib-1.4.1.tar.gz",
    ],
)

local_repository(
    name = "io_bazel_rules_scala",
    path = "../..",
)

load("@io_bazel_rules_scala//:scala_config.bzl", "scala_config")

scala_config(enable_compiler_dependency_tracking = True)

load(
    "@io_bazel_rules_scala//scala:scala.bzl",
    "rules_scala_setup",
    "rules_scala_toolchain_deps_repositories",
)
load(
    "@io_bazel_rules_scala//scala:scala_cross_version.bzl",
    "default_maven_server_urls",
)
load(
    "@io_bazel_rules_scala//scala:scala_maven_import_external.bzl",
    "scala_maven_import_external",
)
load("@io_bazel_rules_scala_config//:config.bzl", "SCALA_VERSION")

http_jar(
    name = "scala_compiler_srcjar",
    sha256 = "95c217cc87ee846b39990e0a9c273824a384dffbac57df84d466f866df4a91ea",
    url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.16/scala-compiler-2.12.16-sources.jar",
)

scala_maven_import_external(
    name = "scala_library",
    artifact = "org.scala-lang:scala-library:%s" % SCALA_VERSION,
    licenses = ["notice"],
    server_urls = default_maven_server_urls(),
)

scala_maven_import_external(
    name = "scala_compiler",
    artifact = "org.scala-lang:scala-compiler:%s" % SCALA_VERSION,
    licenses = ["notice"],
    server_urls = default_maven_server_urls(),
)

scala_maven_import_external(
    name = "scala_reflect",
    artifact = "org.scala-lang:scala-reflect:%s" % SCALA_VERSION,
    licenses = ["notice"],
    server_urls = default_maven_server_urls(),
)

srcjars_by_version = {
    # Invalid
    "2.12.11": [],
    # Invalid
    "2.12.12": {
        "lable": "foo",
    },
    # Invalid
    "2.12.13": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.13/scala-compiler-2.12.13-sources.jar",
        "label": "foo",
    },
    "2.12.14": {
        "urls": ["https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.14/scala-compiler-2.12.14-sources.jar"],
        "integrity": "sha384-yKJTudaHM2dA+VM//elLxhEfOmyCYRHzbLlQcf5jlrR+G5FEW+fBW/b794mQLMOX",
    },
    "2.12.15": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.15/scala-compiler-2.12.15-sources.jar",
        "sha256": "65f783f1fbef7de661224f607ac07ca03c5d19acfdb7f2234ff8def1e79b5cd8",
    },
    "2.12.16": {
        "label": "@scala_compiler_srcjar//jar:downloaded.jar",
    },
    "2.12.17": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.17/scala-compiler-2.12.17-sources.jar?foo",
    },
    "2.12.18": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.18/scala-compiler-2.12.18-sources.jar?foo",
    },
    "2.13.11": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.11/scala-compiler-2.13.11-sources.jar?foo",
    },
    "2.13.12": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.12/scala-compiler-2.13.12-sources.jar?foo",
    },
}

rules_scala_setup(scala_compiler_srcjar = srcjars_by_version[SCALA_VERSION])

rules_scala_toolchain_deps_repositories(
    fetch_sources = True,
    validate_scala_version = False,
)

register_toolchains(":dt_scala_toolchain")

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()

load("@io_bazel_rules_scala//scala:toolchains.bzl", "scala_register_toolchains")

scala_register_toolchains()
