workspace(name = "test_dt_patches")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_jar")

http_archive(
    name = "bazel_skylib",
    sha256 = "b8a1527901774180afc798aeb28c4634bdccf19c4d98e7bdd1ce79d1fe9aaad7",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.4.1/bazel-skylib-1.4.1.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.4.1/bazel-skylib-1.4.1.tar.gz",
    ],
)

http_archive(
    name = "rules_python",
    sha256 = "ca77768989a7f311186a29747e3e95c936a41dffac779aff6b443db22290d913",
    strip_prefix = "rules_python-0.36.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.36.0/rules_python-0.36.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

local_repository(
    name = "io_bazel_rules_scala",
    path = "../..",
)

load("@io_bazel_rules_scala//:scala_config.bzl", "scala_config")

scala_config(enable_compiler_dependency_tracking = True)

load(
    "@io_bazel_rules_scala//scala:scala.bzl",
    "rules_scala_setup",
    "rules_scala_toolchain_deps_repositories",
    "scala_toolchains_repo",
)
load(
    "@io_bazel_rules_scala//scala:scala_cross_version.bzl",
    "default_maven_server_urls",
)
load(
    "@io_bazel_rules_scala//scala:scala_maven_import_external.bzl",
    "scala_maven_import_external",
)
load("@io_bazel_rules_scala_config//:config.bzl", "SCALA_VERSION")

http_jar(
    name = "scala_compiler_srcjar",
    sha256 = "95c217cc87ee846b39990e0a9c273824a384dffbac57df84d466f866df4a91ea",
    url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.16/scala-compiler-2.12.16-sources.jar",
)

http_jar(
    name = "scala3_compiler_srcjar",
    sha256 = "3c413efa9a2921ef59da7f065c445ae1b6b97057cbbc6b16957ad052a575a3ce",
    url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.4.3/scala3-compiler_3-3.4.3-sources.jar",
)

scala_maven_import_external(
    name = "scala_library",
    artifact = "org.scala-lang:scala-library:%s" % SCALA_VERSION if SCALA_VERSION.startswith("2.") else "org.scala-lang:scala3-library_3:%s" % SCALA_VERSION,
    licenses = ["notice"],
    server_urls = default_maven_server_urls(),
)

scala_maven_import_external(
    name = "scala_compiler",
    artifact = "org.scala-lang:scala-compiler:%s" % SCALA_VERSION if SCALA_VERSION.startswith("2.") else "org.scala-lang:scala3-compiler_3:%s" % SCALA_VERSION,
    licenses = ["notice"],
    server_urls = default_maven_server_urls(),
)

# Scala 2 only
scala_maven_import_external(
    name = "scala_reflect",
    artifact = "org.scala-lang:scala-reflect:%s" % SCALA_VERSION,
    licenses = ["notice"],
    server_urls = default_maven_server_urls(),
)

# Scala 3 only
scala_maven_import_external(
    name = "scala3_interfaces",
    artifact = "org.scala-lang:scala3-interfaces:%s" % SCALA_VERSION,
    licenses = ["notice"],
    server_urls = default_maven_server_urls(),
)

scala_maven_import_external(
    name = "scala2_library",
    artifact = "org.scala-lang:scala-library:2.13.15",
    licenses = ["notice"],
    server_urls = default_maven_server_urls(),
)

scala_maven_import_external(
    name = "tasty_core",
    artifact = "org.scala-lang:tasty-core_3:%s" % SCALA_VERSION,
    licenses = ["notice"],
    server_urls = default_maven_server_urls(),
)

scala_maven_import_external(
    name = "scala_asm",
    artifact = "org.scala-lang.modules:scala-asm:9.7.0-scala-2",
    licenses = ["notice"],
    server_urls = default_maven_server_urls(),
)

scala_maven_import_external(
    name = "sbt_compiler_interface",
    artifact = "org.scala-sbt:compiler-interface:1.9.6",
    licenses = ["notice"],
    server_urls = default_maven_server_urls(),
)

srcjars_by_version = {
    # Invalid
    "2.12.11": [],
    # Invalid
    "2.12.12": {
        "lable": "foo",
    },
    # Invalid
    "2.12.13": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.13/scala-compiler-2.12.13-sources.jar",
        "label": "foo",
    },
    "2.12.14": {
        "urls": ["https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.14/scala-compiler-2.12.14-sources.jar"],
        "integrity": "sha384-yKJTudaHM2dA+VM//elLxhEfOmyCYRHzbLlQcf5jlrR+G5FEW+fBW/b794mQLMOX",
    },
    "2.12.15": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.15/scala-compiler-2.12.15-sources.jar",
        "sha256": "65f783f1fbef7de661224f607ac07ca03c5d19acfdb7f2234ff8def1e79b5cd8",
    },
    "2.12.16": {
        "label": "@scala_compiler_srcjar//jar:downloaded.jar",
    },
    "2.12.17": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.17/scala-compiler-2.12.17-sources.jar?foo",
    },
    "2.12.18": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.18/scala-compiler-2.12.18-sources.jar?foo",
    },
    "2.12.19": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.19/scala-compiler-2.12.19-sources.jar?foo",
    },
    "2.12.20": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20-sources.jar?foo",
    },
    "2.13.11": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.11/scala-compiler-2.13.11-sources.jar?foo",
    },
    "2.13.12": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.12/scala-compiler-2.13.12-sources.jar?foo",
    },
    "2.13.14": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.14/scala-compiler-2.13.14-sources.jar?foo",
    },
    "2.13.15": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.15/scala-compiler-2.13.15-sources.jar?foo",
    },
    "3.1.3": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.1.3/scala3-compiler_3-3.1.3-sources.jar",
        "integrity": "sha384-4J2ihR1QSdP5cvL3y2OUfw4uUX/hsQqcPlJV+IrQdsM/soiIAYfoEeIEt6vl3xBk",
    },
    "3.2.2": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.2.2/scala3-compiler_3-3.2.2-sources.jar",
        "sha256": "669d580fc4a8d3c2e2d13d5735ae9be05d567613fe44482de5bcc5e2e2ee89ea",
    },
    "3.3.4": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.3.4/scala3-compiler_3-3.3.4-sources.jar",
    },
    "3.4.3": {
        "label": "@scala3_compiler_srcjar//jar:downloaded.jar",
    },
    "3.5.2": {
        "url": "https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.5.2/scala3-compiler_3-3.5.2-sources.jar",
    },
}

rules_scala_setup(scala_compiler_srcjar = srcjars_by_version[SCALA_VERSION])

rules_scala_toolchain_deps_repositories(
    fetch_sources = True,
    validate_scala_version = False,
)

scala_toolchains_repo()

register_toolchains(":dt_scala_toolchain")

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies")

rules_proto_dependencies()

load("@rules_proto//proto:setup.bzl", "rules_proto_setup")

rules_proto_setup()

load("@rules_proto//proto:toolchains.bzl", "rules_proto_toolchains")

rules_proto_toolchains()

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

load("@io_bazel_rules_scala//scala:toolchains.bzl", "scala_register_toolchains")

scala_register_toolchains()
