package(default_visibility = ["//visibility:public"])
load("//scala:scala_import.bzl", "scala_import")

scala_import(
    name = "scalatest",
    jars = [],
    exports = [
        "@io_bazel_rules_scala_scalatest",
        "@io_bazel_rules_scala_scalactic",
    ],
)
