package(default_visibility = ["//visibility:public"])

alias(
    name = "scalatest",
    actual = "//testing/toolchain:scalatest_classpath",
    deprecation = "Use //testing/toolchain:scalatest_classpath directly",
)
