package(default_visibility = ["//visibility:public"])

load("//scala:scala_import.bzl", "scala_import")

scala_import(
    name = "scalatest",
    jars = [],
    exports = [
        "//scala/scalatest/toolchain:scalatest_classapth",
    ],
)
