load("//twitter_scrooge:twitter_scrooge.bzl", "scrooge_scala_library")

scrooge_scala_library(
  name = "absolute_prefixes_test",
  deps = [
    "//test/src/main/scala/scala/test/twitter_scrooge/prefix_test/a/b/c/d",
    "//test/src/main/scala/scala/test/twitter_scrooge/prefix_test/e/f/b/c/d",
  ],
  visibility = ["//visibility:public"],
)
