load("//scala_proto:scala_proto.bzl", "scala_proto_library")

scala_proto_library(
    name = "sample_scala_proto",
    visibility = ["//visibility:public"],
    deps = ["@proto_cross_repo_boundary//:sample_proto"],
)
