load("//scala:scala.bzl", "scala_library_for_plugin_bootstrapping")

scala_library_for_plugin_bootstrapping(
    name = "numeric",
    srcs = glob(["*.scala"]),
    scala_version = "3.6.2",
    visibility = ["//visibility:public"],
)
