load("//scala:scala.bzl", "scala_library", "scala_test")

scala_test(
    name = "resource_jars",
    srcs = ["TestResourceJars.scala"],
    resource_jars = ["//test/src/main/resources/scalarules/test:hellos-and-byes.jar"],
)
