load("@io_bazel_rules_scala//thrift:thrift.bzl", "thrift_library")

thrift_library(
    name = "bare_jar_2",
    srcs = ["//src/main/resources/scalarules/test:Baz.thrift"],
    visibility = ["//visibility:public"],
)
