load("@io_bazel_rules_scala//thrift:thrift.bzl", "thrift_library")

thrift_library(
    name = "bare_jar_2",
    external_jars = [
        "bare-thrift-2.jar",
    ],
    visibility = ["//visibility:public"],
)
