load("//scala:scala.bzl", "scala_library", "scala_test")

scala_test(
    name = "directory_utils",
    srcs = [
        "DeleteDirectoryTest.scala",
    ],
    deps = [
        "@io_bazel_rules_scala//src/java/io/bazel/rulesscala/io_utils",
    ],
)
