load("//thrift:thrift.bzl", "thrift_library")

thrift_library(
  name = "d",
  srcs = ["B.thrift"],
  absolute_prefixes = ["prefix_test/a", "prefix_test/e/f"],
  visibility = ["//visibility:public"],
)
