load("//scala:scala.bzl", "scala_binary", "scala_library")
scala_binary(
    main_class = "scala.test.large_classpath.ObjectWithLargeClasspath",
    name = "largeClasspath",
    srcs = ["ObjectWithLargeClasspath.scala"],
    deps = [
        ":empty1",
        ":empty2",
        ":empty3",
        ":empty4",
        ":empty5",
        ":empty6",
        ":empty7",
        ":empty8",
        ":empty9",
        ":empty10",
        ":empty11",
        ":empty12",
        ":empty13",
        ":empty14",
        ":empty15",
        ":empty16",
        ":empty17",
        ":empty18",
        ":empty19",
        ":empty20",
        ":empty21",
        ":empty22",
        ":empty23",
        ":empty24",
        ":empty25",
        ":empty26",
        ":empty27",
        ":empty28",
        ":empty29",
        ":empty30",
        ":empty31",
        ":empty32",
        ":empty33",
        ":empty34",
        ":empty35",
        ":empty36",
        ":empty37",
        ":empty38",
        ":empty39",
        ":empty40",
        ":empty41",
        ":empty42",
        ":empty43",
        ":empty44",
        ":empty45",
        ":empty46",
        ":empty47",
        ":empty48",
        ":empty49",
        ":empty50",
        ":empty51",
        ":empty52",
        ":empty53",
        ":empty54",
        ":empty55",
        ":empty56",
        ":empty57",
        ":empty58",
        ":empty59",
        ":empty60",
        ":empty61",
        ":empty62",
        ":empty63",
        ":empty64",
        ":empty65",
        ":empty66",
        ":empty67",
        ":empty68",
        ":empty69",
        ":empty70",
        ":empty71",
        ":empty72",
        ":empty73",
        ":empty74",
        ":empty75",
        ":empty76",
        ":empty77",
        ":empty78",
        ":empty79",
        ":empty80",
        ":empty81",
        ":empty82",
        ":empty83",
        ":empty84",
        ":empty85",
        ":empty86",
        ":empty87",
        ":empty88",
        ":empty89",
        ":empty90",
        ":empty91",
        ":empty92",
        ":empty93",
        ":empty94",
        ":empty95",
        ":empty96",
        ":empty97",
        ":empty98",
        ":empty99",
        ":empty100",
        ":empty101",
        ":empty102",
        ":empty103",
        ":empty104",
        ":empty105",
        ":empty106",
        ":empty107",
        ":empty108",
        ":empty109",
        ":empty110",
        ":empty111",
        ":empty112",
        ":empty113",
        ":empty114",
        ":empty115",
        ":empty116",
        ":empty117",
        ":empty118",
        ":empty119",
        ":empty120",
        ":empty121",
        ":empty122",
        ":empty123",
        ":empty124",
        ":empty125",
        ":empty126",
        ":empty127",
        ":empty128",
        ":empty129",
        ":empty130",
        ":empty131",
        ":empty132",
        ":empty133",
        ":empty134",
        ":empty135",
        ":empty136",
        ":empty137",
        ":empty138",
        ":empty139",
        ":empty140",
        ":empty141",
        ":empty142",
        ":empty143",
        ":empty144",
        ":empty145",
        ":empty146",
        ":empty147",
        ":empty148",
        ":empty149",
        ":empty150",
        ":empty151",
        ":empty152",
        ":empty153",
        ":empty154",
        ":empty155",
        ":empty156",
        ":empty157",
        ":empty158",
        ":empty159",
        ":empty160",
        ":empty161",
        ":empty162",
        ":empty163",
        ":empty164",
        ":empty165",
        ":empty166",
        ":empty167",
        ":empty168",
        ":empty169",
        ":empty170",
        ":empty171",
        ":empty172",
        ":empty173",
        ":empty174",
        ":empty175",
        ":empty176",
        ":empty177",
        ":empty178",
        ":empty179",
        ":empty180",
        ":empty181",
        ":empty182",
        ":empty183",
        ":empty184",
        ":empty185",
        ":empty186",
        ":empty187",
        ":empty188",
        ":empty189",
        ":empty190",
        ":empty191",
        ":empty192",
        ":empty193",
        ":empty194",
        ":empty195",
        ":empty196",
        ":empty197",
        ":empty198",
        ":empty199",
        ":empty200",
        ":empty201",
        ":empty202",
        ":empty203",
        ":empty204",
        ":empty205",
        ":empty206",
        ":empty207",
        ":empty208",
        ":empty209",
        ":empty210",
        ":empty211",
        ":empty212",
        ":empty213",
        ":empty214",
        ":empty215",
        ":empty216",
        ":empty217",
        ":empty218",
        ":empty219",
        ":empty220",
        ":empty221",
        ":empty222",
        ":empty223",
        ":empty224",
        ":empty225",
        ":empty226",
        ":empty227",
        ":empty228",
        ":empty229",
        ":empty230",
        ":empty231",
        ":empty232",
        ":empty233",
        ":empty234",
        ":empty235",
        ":empty236",
        ":empty237",
        ":empty238",
        ":empty239",
        ":empty240",
        ":empty241",
        ":empty242",
        ":empty243",
        ":empty244",
        ":empty245",
        ":empty246",
        ":empty247",
        ":empty248",
        ":empty249",
        ":empty250",
        ":empty251",
        ":empty252",
        ":empty253",
        ":empty254",
        ":empty255",
        ":empty256",
        ":empty257",
        ":empty258",
        ":empty259",
        ":empty260",
        ":empty261",
        ":empty262",
        ":empty263",
        ":empty264",
        ":empty265",
        ":empty266",
        ":empty267",
        ":empty268",
        ":empty269",
        ":empty270",
        ":empty271",
        ":empty272",
        ":empty273",
        ":empty274",
        ":empty275",
        ":empty276",
        ":empty277",
        ":empty278",
        ":empty279",
        ":empty280",
        ":empty281",
        ":empty282",
        ":empty283",
        ":empty284",
        ":empty285",
        ":empty286",
        ":empty287",
        ":empty288",
        ":empty289",
        ":empty290",
        ":empty291",
        ":empty292",
        ":empty293",
        ":empty294",
        ":empty295",
        ":empty296",
        ":empty297",
        ":empty298",
        ":empty299",
        ":empty300",
        ":empty301",
        ":empty302",
        ":empty303",
        ":empty304",
        ":empty305",
        ":empty306",
        ":empty307",
        ":empty308",
        ":empty309",
        ":empty310",
        ":empty311",
        ":empty312",
        ":empty313",
        ":empty314",
        ":empty315",
        ":empty316",
        ":empty317",
        ":empty318",
        ":empty319",
        ":empty320",
        ":empty321",
        ":empty322",
        ":empty323",
        ":empty324",
        ":empty325",
        ":empty326",
        ":empty327",
        ":empty328",
        ":empty329",
        ":empty330",
        ":empty331",
        ":empty332",
        ":empty333",
        ":empty334",
        ":empty335",
        ":empty336",
        ":empty337",
        ":empty338",
        ":empty339",
        ":empty340",
        ":empty341",
        ":empty342",
        ":empty343",
        ":empty344",
        ":empty345",
        ":empty346",
        ":empty347",
        ":empty348",
        ":empty349",
        ":empty350",
        ":empty351",
        ":empty352",
        ":empty353",
        ":empty354",
        ":empty355",
        ":empty356",
        ":empty357",
        ":empty358",
        ":empty359",
        ":empty360",
        ":empty361",
        ":empty362",
        ":empty363",
        ":empty364",
        ":empty365",
        ":empty366",
        ":empty367",
        ":empty368",
        ":empty369",
        ":empty370",
        ":empty371",
        ":empty372",
        ":empty373",
        ":empty374",
        ":empty375",
        ":empty376",
        ":empty377",
        ":empty378",
        ":empty379",
        ":empty380",
        ":empty381",
        ":empty382",
        ":empty383",
        ":empty384",
        ":empty385",
        ":empty386",
        ":empty387",
        ":empty388",
        ":empty389",
        ":empty390",
        ":empty391",
        ":empty392",
        ":empty393",
        ":empty394",
        ":empty395",
        ":empty396",
        ":empty397",
        ":empty398",
        ":empty399",
        ":empty400",
        ":empty401",
        ":empty402",
        ":empty403",
        ":empty404",
        ":empty405",
        ":empty406",
        ":empty407",
        ":empty408",
        ":empty409",
        ":empty410",
        ":empty411",
        ":empty412",
        ":empty413",
        ":empty414",
        ":empty415",
        ":empty416",
        ":empty417",
        ":empty418",
        ":empty419",
        ":empty420",
        ":empty421",
        ":empty422",
        ":empty423",
        ":empty424",
        ":empty425",
        ":empty426",
        ":empty427",
        ":empty428",
        ":empty429",
        ":empty430",
        ":empty431",
        ":empty432",
        ":empty433",
        ":empty434",
        ":empty435",
        ":empty436",
        ":empty437",
        ":empty438",
        ":empty439",
        ":empty440",
        ":empty441",
        ":empty442",
        ":empty443",
        ":empty444",
        ":empty445",
        ":empty446",
        ":empty447",
        ":empty448",
        ":empty449",
        ":empty450",
    ],
     
)
    
scala_library(name = "empty1")
scala_library(name = "empty2")
scala_library(name = "empty3")
scala_library(name = "empty4")
scala_library(name = "empty5")
scala_library(name = "empty6")
scala_library(name = "empty7")
scala_library(name = "empty8")
scala_library(name = "empty9")
scala_library(name = "empty10")
scala_library(name = "empty11")
scala_library(name = "empty12")
scala_library(name = "empty13")
scala_library(name = "empty14")
scala_library(name = "empty15")
scala_library(name = "empty16")
scala_library(name = "empty17")
scala_library(name = "empty18")
scala_library(name = "empty19")
scala_library(name = "empty20")
scala_library(name = "empty21")
scala_library(name = "empty22")
scala_library(name = "empty23")
scala_library(name = "empty24")
scala_library(name = "empty25")
scala_library(name = "empty26")
scala_library(name = "empty27")
scala_library(name = "empty28")
scala_library(name = "empty29")
scala_library(name = "empty30")
scala_library(name = "empty31")
scala_library(name = "empty32")
scala_library(name = "empty33")
scala_library(name = "empty34")
scala_library(name = "empty35")
scala_library(name = "empty36")
scala_library(name = "empty37")
scala_library(name = "empty38")
scala_library(name = "empty39")
scala_library(name = "empty40")
scala_library(name = "empty41")
scala_library(name = "empty42")
scala_library(name = "empty43")
scala_library(name = "empty44")
scala_library(name = "empty45")
scala_library(name = "empty46")
scala_library(name = "empty47")
scala_library(name = "empty48")
scala_library(name = "empty49")
scala_library(name = "empty50")
scala_library(name = "empty51")
scala_library(name = "empty52")
scala_library(name = "empty53")
scala_library(name = "empty54")
scala_library(name = "empty55")
scala_library(name = "empty56")
scala_library(name = "empty57")
scala_library(name = "empty58")
scala_library(name = "empty59")
scala_library(name = "empty60")
scala_library(name = "empty61")
scala_library(name = "empty62")
scala_library(name = "empty63")
scala_library(name = "empty64")
scala_library(name = "empty65")
scala_library(name = "empty66")
scala_library(name = "empty67")
scala_library(name = "empty68")
scala_library(name = "empty69")
scala_library(name = "empty70")
scala_library(name = "empty71")
scala_library(name = "empty72")
scala_library(name = "empty73")
scala_library(name = "empty74")
scala_library(name = "empty75")
scala_library(name = "empty76")
scala_library(name = "empty77")
scala_library(name = "empty78")
scala_library(name = "empty79")
scala_library(name = "empty80")
scala_library(name = "empty81")
scala_library(name = "empty82")
scala_library(name = "empty83")
scala_library(name = "empty84")
scala_library(name = "empty85")
scala_library(name = "empty86")
scala_library(name = "empty87")
scala_library(name = "empty88")
scala_library(name = "empty89")
scala_library(name = "empty90")
scala_library(name = "empty91")
scala_library(name = "empty92")
scala_library(name = "empty93")
scala_library(name = "empty94")
scala_library(name = "empty95")
scala_library(name = "empty96")
scala_library(name = "empty97")
scala_library(name = "empty98")
scala_library(name = "empty99")
scala_library(name = "empty100")
scala_library(name = "empty101")
scala_library(name = "empty102")
scala_library(name = "empty103")
scala_library(name = "empty104")
scala_library(name = "empty105")
scala_library(name = "empty106")
scala_library(name = "empty107")
scala_library(name = "empty108")
scala_library(name = "empty109")
scala_library(name = "empty110")
scala_library(name = "empty111")
scala_library(name = "empty112")
scala_library(name = "empty113")
scala_library(name = "empty114")
scala_library(name = "empty115")
scala_library(name = "empty116")
scala_library(name = "empty117")
scala_library(name = "empty118")
scala_library(name = "empty119")
scala_library(name = "empty120")
scala_library(name = "empty121")
scala_library(name = "empty122")
scala_library(name = "empty123")
scala_library(name = "empty124")
scala_library(name = "empty125")
scala_library(name = "empty126")
scala_library(name = "empty127")
scala_library(name = "empty128")
scala_library(name = "empty129")
scala_library(name = "empty130")
scala_library(name = "empty131")
scala_library(name = "empty132")
scala_library(name = "empty133")
scala_library(name = "empty134")
scala_library(name = "empty135")
scala_library(name = "empty136")
scala_library(name = "empty137")
scala_library(name = "empty138")
scala_library(name = "empty139")
scala_library(name = "empty140")
scala_library(name = "empty141")
scala_library(name = "empty142")
scala_library(name = "empty143")
scala_library(name = "empty144")
scala_library(name = "empty145")
scala_library(name = "empty146")
scala_library(name = "empty147")
scala_library(name = "empty148")
scala_library(name = "empty149")
scala_library(name = "empty150")
scala_library(name = "empty151")
scala_library(name = "empty152")
scala_library(name = "empty153")
scala_library(name = "empty154")
scala_library(name = "empty155")
scala_library(name = "empty156")
scala_library(name = "empty157")
scala_library(name = "empty158")
scala_library(name = "empty159")
scala_library(name = "empty160")
scala_library(name = "empty161")
scala_library(name = "empty162")
scala_library(name = "empty163")
scala_library(name = "empty164")
scala_library(name = "empty165")
scala_library(name = "empty166")
scala_library(name = "empty167")
scala_library(name = "empty168")
scala_library(name = "empty169")
scala_library(name = "empty170")
scala_library(name = "empty171")
scala_library(name = "empty172")
scala_library(name = "empty173")
scala_library(name = "empty174")
scala_library(name = "empty175")
scala_library(name = "empty176")
scala_library(name = "empty177")
scala_library(name = "empty178")
scala_library(name = "empty179")
scala_library(name = "empty180")
scala_library(name = "empty181")
scala_library(name = "empty182")
scala_library(name = "empty183")
scala_library(name = "empty184")
scala_library(name = "empty185")
scala_library(name = "empty186")
scala_library(name = "empty187")
scala_library(name = "empty188")
scala_library(name = "empty189")
scala_library(name = "empty190")
scala_library(name = "empty191")
scala_library(name = "empty192")
scala_library(name = "empty193")
scala_library(name = "empty194")
scala_library(name = "empty195")
scala_library(name = "empty196")
scala_library(name = "empty197")
scala_library(name = "empty198")
scala_library(name = "empty199")
scala_library(name = "empty200")
scala_library(name = "empty201")
scala_library(name = "empty202")
scala_library(name = "empty203")
scala_library(name = "empty204")
scala_library(name = "empty205")
scala_library(name = "empty206")
scala_library(name = "empty207")
scala_library(name = "empty208")
scala_library(name = "empty209")
scala_library(name = "empty210")
scala_library(name = "empty211")
scala_library(name = "empty212")
scala_library(name = "empty213")
scala_library(name = "empty214")
scala_library(name = "empty215")
scala_library(name = "empty216")
scala_library(name = "empty217")
scala_library(name = "empty218")
scala_library(name = "empty219")
scala_library(name = "empty220")
scala_library(name = "empty221")
scala_library(name = "empty222")
scala_library(name = "empty223")
scala_library(name = "empty224")
scala_library(name = "empty225")
scala_library(name = "empty226")
scala_library(name = "empty227")
scala_library(name = "empty228")
scala_library(name = "empty229")
scala_library(name = "empty230")
scala_library(name = "empty231")
scala_library(name = "empty232")
scala_library(name = "empty233")
scala_library(name = "empty234")
scala_library(name = "empty235")
scala_library(name = "empty236")
scala_library(name = "empty237")
scala_library(name = "empty238")
scala_library(name = "empty239")
scala_library(name = "empty240")
scala_library(name = "empty241")
scala_library(name = "empty242")
scala_library(name = "empty243")
scala_library(name = "empty244")
scala_library(name = "empty245")
scala_library(name = "empty246")
scala_library(name = "empty247")
scala_library(name = "empty248")
scala_library(name = "empty249")
scala_library(name = "empty250")
scala_library(name = "empty251")
scala_library(name = "empty252")
scala_library(name = "empty253")
scala_library(name = "empty254")
scala_library(name = "empty255")
scala_library(name = "empty256")
scala_library(name = "empty257")
scala_library(name = "empty258")
scala_library(name = "empty259")
scala_library(name = "empty260")
scala_library(name = "empty261")
scala_library(name = "empty262")
scala_library(name = "empty263")
scala_library(name = "empty264")
scala_library(name = "empty265")
scala_library(name = "empty266")
scala_library(name = "empty267")
scala_library(name = "empty268")
scala_library(name = "empty269")
scala_library(name = "empty270")
scala_library(name = "empty271")
scala_library(name = "empty272")
scala_library(name = "empty273")
scala_library(name = "empty274")
scala_library(name = "empty275")
scala_library(name = "empty276")
scala_library(name = "empty277")
scala_library(name = "empty278")
scala_library(name = "empty279")
scala_library(name = "empty280")
scala_library(name = "empty281")
scala_library(name = "empty282")
scala_library(name = "empty283")
scala_library(name = "empty284")
scala_library(name = "empty285")
scala_library(name = "empty286")
scala_library(name = "empty287")
scala_library(name = "empty288")
scala_library(name = "empty289")
scala_library(name = "empty290")
scala_library(name = "empty291")
scala_library(name = "empty292")
scala_library(name = "empty293")
scala_library(name = "empty294")
scala_library(name = "empty295")
scala_library(name = "empty296")
scala_library(name = "empty297")
scala_library(name = "empty298")
scala_library(name = "empty299")
scala_library(name = "empty300")
scala_library(name = "empty301")
scala_library(name = "empty302")
scala_library(name = "empty303")
scala_library(name = "empty304")
scala_library(name = "empty305")
scala_library(name = "empty306")
scala_library(name = "empty307")
scala_library(name = "empty308")
scala_library(name = "empty309")
scala_library(name = "empty310")
scala_library(name = "empty311")
scala_library(name = "empty312")
scala_library(name = "empty313")
scala_library(name = "empty314")
scala_library(name = "empty315")
scala_library(name = "empty316")
scala_library(name = "empty317")
scala_library(name = "empty318")
scala_library(name = "empty319")
scala_library(name = "empty320")
scala_library(name = "empty321")
scala_library(name = "empty322")
scala_library(name = "empty323")
scala_library(name = "empty324")
scala_library(name = "empty325")
scala_library(name = "empty326")
scala_library(name = "empty327")
scala_library(name = "empty328")
scala_library(name = "empty329")
scala_library(name = "empty330")
scala_library(name = "empty331")
scala_library(name = "empty332")
scala_library(name = "empty333")
scala_library(name = "empty334")
scala_library(name = "empty335")
scala_library(name = "empty336")
scala_library(name = "empty337")
scala_library(name = "empty338")
scala_library(name = "empty339")
scala_library(name = "empty340")
scala_library(name = "empty341")
scala_library(name = "empty342")
scala_library(name = "empty343")
scala_library(name = "empty344")
scala_library(name = "empty345")
scala_library(name = "empty346")
scala_library(name = "empty347")
scala_library(name = "empty348")
scala_library(name = "empty349")
scala_library(name = "empty350")
scala_library(name = "empty351")
scala_library(name = "empty352")
scala_library(name = "empty353")
scala_library(name = "empty354")
scala_library(name = "empty355")
scala_library(name = "empty356")
scala_library(name = "empty357")
scala_library(name = "empty358")
scala_library(name = "empty359")
scala_library(name = "empty360")
scala_library(name = "empty361")
scala_library(name = "empty362")
scala_library(name = "empty363")
scala_library(name = "empty364")
scala_library(name = "empty365")
scala_library(name = "empty366")
scala_library(name = "empty367")
scala_library(name = "empty368")
scala_library(name = "empty369")
scala_library(name = "empty370")
scala_library(name = "empty371")
scala_library(name = "empty372")
scala_library(name = "empty373")
scala_library(name = "empty374")
scala_library(name = "empty375")
scala_library(name = "empty376")
scala_library(name = "empty377")
scala_library(name = "empty378")
scala_library(name = "empty379")
scala_library(name = "empty380")
scala_library(name = "empty381")
scala_library(name = "empty382")
scala_library(name = "empty383")
scala_library(name = "empty384")
scala_library(name = "empty385")
scala_library(name = "empty386")
scala_library(name = "empty387")
scala_library(name = "empty388")
scala_library(name = "empty389")
scala_library(name = "empty390")
scala_library(name = "empty391")
scala_library(name = "empty392")
scala_library(name = "empty393")
scala_library(name = "empty394")
scala_library(name = "empty395")
scala_library(name = "empty396")
scala_library(name = "empty397")
scala_library(name = "empty398")
scala_library(name = "empty399")
scala_library(name = "empty400")
scala_library(name = "empty401")
scala_library(name = "empty402")
scala_library(name = "empty403")
scala_library(name = "empty404")
scala_library(name = "empty405")
scala_library(name = "empty406")
scala_library(name = "empty407")
scala_library(name = "empty408")
scala_library(name = "empty409")
scala_library(name = "empty410")
scala_library(name = "empty411")
scala_library(name = "empty412")
scala_library(name = "empty413")
scala_library(name = "empty414")
scala_library(name = "empty415")
scala_library(name = "empty416")
scala_library(name = "empty417")
scala_library(name = "empty418")
scala_library(name = "empty419")
scala_library(name = "empty420")
scala_library(name = "empty421")
scala_library(name = "empty422")
scala_library(name = "empty423")
scala_library(name = "empty424")
scala_library(name = "empty425")
scala_library(name = "empty426")
scala_library(name = "empty427")
scala_library(name = "empty428")
scala_library(name = "empty429")
scala_library(name = "empty430")
scala_library(name = "empty431")
scala_library(name = "empty432")
scala_library(name = "empty433")
scala_library(name = "empty434")
scala_library(name = "empty435")
scala_library(name = "empty436")
scala_library(name = "empty437")
scala_library(name = "empty438")
scala_library(name = "empty439")
scala_library(name = "empty440")
scala_library(name = "empty441")
scala_library(name = "empty442")
scala_library(name = "empty443")
scala_library(name = "empty444")
scala_library(name = "empty445")
scala_library(name = "empty446")
scala_library(name = "empty447")
scala_library(name = "empty448")
scala_library(name = "empty449")
scala_library(name = "empty450")
