load("//scala:scala.bzl", "scala_binary")

scala_binary(
    name = "fetch_sources",
    srcs = [ "FetchSources.scala" ],
    main_class = "scalarules.test.src.main.scala.scalarules.test.fetch_sources.FetchSources",
    deps = [ "@com_google_guava_guava_21_0//jar" ]
)
