java_library(
    name = "io_utils",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    )

filegroup(
    name = "sources",
    data = glob(["**"]),
    visibility = ["//visibility:public"]
    )