java_test(
    name = "jdeps",
    srcs = ["JdepsWriterTest.java"],
    test_class = "jdeps.JdepsWriterTest",
    deps = [
        "//src/java/io/bazel/rulesscala/jdeps",
        "@bazel_tools//src/main/protobuf:deps_java_proto",
        "@com_google_protobuf//:protobuf_java",
        "@io_bazel_rules_scala_junit_junit",
    ],
)
