load("//scala:scala.bzl", "scala_specs2_junit_test")

scala_specs2_junit_test(
    name = "ArchiveEntriesTest",
    srcs = ["ArchiveEntriesTest.scala"],
    suffixes = ["Test"],
    deps = [
        "//src/java/io/bazel/rulesscala/test_discovery",
    ],
)
