java_import(
  name = "parser_combinators",
  jars = ["@scala//:lib/scala-parser-combinators_2.11-1.0.4.jar"],
  visibility = ["//visibility:public"],
)

java_import(
  name = "scala_xml",
  jars = ["@scala//:lib/scala-xml_2.11-1.0.4.jar"],
  visibility = ["//visibility:public"],
)

java_import(
  name = "scala_compiler",
  jars = ["@scala//:lib/scala-compiler.jar"],
  visibility = ["//visibility:public"],
)

java_import(
  name = "scala_library",
  jars = ["@scala//:lib/scala-library.jar"],
  visibility = ["//visibility:public"],
)

java_import(
  name = "scala_reflect",
  jars = ["@scala//:lib/scala-reflect.jar"],
  visibility = ["//visibility:public"],
)
