#!/bin/zsh -e

printf "\u001b[1;39m:::\u001b[0m\n"
printf "\u001b[1;39m  test file: $0\u001b[0m\n"
printf "\u001b[1;39m:::\u001b[0m\n"

error() {
    set +x
    printf "\u001b[1;31m::FAILURE::\u001b[0m $FILE:$2 exited with code $1\n"
}

finish() {
    set +x
    [ $1 != 0 ] || printf "\u001b[1;32m::SUCCESS::\u001b[0m\n"
}

trap 'error $? $LINENO' ERR
trap 'finish $?' EXIT

set -x

bazel build //test/crossbuild:lib
bazel build //test/crossbuild:lib2111
bazel build //test/crossbuild:lib212

bazel build //test/crossbuild:repl
bazel build //test/crossbuild:repl212

bazel test //test/crossbuild:test
bazel test //test/crossbuild:test212
bazel test //test/crossbuild:test2124

bazel run //test/crossbuild:binary
bazel run //test/crossbuild:binary212

bazel build //test/crossbuild:macro
bazel build //test/crossbuild:macro212

bazel test //test/crossbuild:junit
